### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by Dsapalov** [sidlatau/flutter_document_picker#27] opened 2019-05-30 09:49 UTC
Hello
  after adding flutter_document_picker to my clean project have problem:
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET flutter_document_picker OF PROJECT Pods WITH CONFIGURATION Debug ===
    **/Users/denis/Documents/work/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_document_picker-3.0.0/ios/Classes/FlutterDocumentPickerPlugin.m:2:9: fatal error: 'flutter_document_picker/flutter_document_picker-Swift.h' file not found
    #import <flutter_document_picker/flutter_document_picker-Swift.h>**
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.

My pubspec.yaml :
dependencies:
  flutter:
    **sdk: flutter
      flutter_document_picker: ^3.0.0**

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

Thank you.

**Comment by sidlatau** [comment] 2019-06-13 20:02
Duplicate of Issue #21

**Closed by sidlatau** 2019-06-13 20:02 UTC
