### ISSUE TITLE
BREAKING ISSUE! Cannot resolve dependencies. Causes builds to fail

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [sidlatau/flutter_document_picker#13] opened 2018-10-18 22:00 UTC
Hi, yesterday, my project stopped building and it threw an error, which i tracked down to be caused by 2 packages. [flutter_email_sender](https://github.com/sidlatau/flutter_email_sender), and [flutter_document_sender](https://github.com/sidlatau/flutter_document_picker). 
![carbon 2](https://user-images.githubusercontent.com/23037821/47186520-aad17e80-d2e5-11e8-96b7-9c4ea883afaf.png)
![carbon 3](https://user-images.githubusercontent.com/23037821/47186521-ab6a1500-d2e5-11e8-95c4-7bb9ea133863.png)
The first one was resolved after switching the target sdk version to 28, although i doubt that's a real fix. I however don't know if this is related to your project or not. Once the first one was resolved, I received the second one. Which I tracked down to these 2 packages. I'm not sure why it's causing it, but after removing the 2 packages from my dependencies, the project builds. I tested this in a completely separate simple project with only 3 widgets and no external dependencies and simply added flutter_document_picker to the pubspec.yaml and the project would no longer build with the error below.
```
Unable to resolve dependency for ':app@dynamicProfile/compileClasspath': Could not resolve project :flutter_document_picker.

Unable to resolve dependency for ':app@dynamicProfileUnitTest/compileClasspath': Could not resolve project :flutter_document_picker.

Unable to resolve dependency for ':app@profile/compileClasspath': Could not resolve project :flutter_document_picker.

Unable to resolve dependency for ':app@profileUnitTest/compileClasspath': Could not resolve project :flutter_document_picker.

Unable to resolve dependency for ':app@dynamicRelease/compileClasspath': Could not resolve project :flutter_document_picker.

Unable to resolve dependency for ':app@dynamicReleaseUnitTest/compileClasspath': Could not resolve project :flutter_document_picker.
```

I'm currently using `flutter_document_picker: ^1.0.1`

**Comment by ThinkDigitalRepair** [comment] 2018-10-18 22:05
Do you want me to open up an issue on the other package as well?

**Comment by ThinkDigitalRepair** [comment] 2018-10-19 07:10
I had 27. I updated to 28 and it fixed the first problem, but not the
second.

**Comment by ThinkDigitalRepair** [comment] 2018-10-19 19:51
Here's my gradle config.
https://gist.github.com/ThinkDigitalRepair/4be1b51a332884fddfed696bdda71188

**Comment by sidlatau** [comment] 2018-10-20 17:39
I am unable to reproduce the problem. This second error is very general. How have you tracked that this problem is caused by this plugin? Does the app works without it?

**Comment by ThinkDigitalRepair** [comment] 2018-10-20 17:41
My app works when I remove your two packages as dependencies. In a separate
app, I simply added the dependency and it wont compile.

**Comment by sidlatau** [comment] 2018-10-20 18:31
Hm, are you using Kotlin, or Java in your apps? I have updated Kotlin version in the plugin to 1.2.71 - maybe that could be a reason.

**Comment by ThinkDigitalRepair** [comment] 2018-10-20 18:34
I use Java only personally.

On Oct 20, 2018 11:31 AM, "sidlatau" <notifications@github.com> wrote:

Hm, are you using Kotlin, or Java in your apps? I have updated Kotlin
version in the plugin to 1.2.71 - maybe that could be a reason.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sidlatau/flutter_document_picker/issues/13#issuecomment-431607077>,
or mute the thread

**Comment by sidlatau** [comment] 2018-10-20 18:42
One more question - what version of Android Studio and gradle are you using?
I tested plugin with the latest versions:
Android Studio: 3.2.1
Gradle: `com.android.tools.build:gradle:3.2.1`

**Comment by ThinkDigitalRepair** [comment] 2018-10-20 18:50
That's what I'm using as well

**Comment by sidlatau** [comment] 2018-10-20 19:19
Hm, interesting, I just created new flutter app which use Java only, added plugin and it works OK. So maybe it is not related to the Kotlin. Trying to figure out what else could be different in your and mine apps. What version of gradle wrapper are you using? Mine is `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip` (`gradle-wrapper.properties`)

Also maybe there could conflicts with other libraries - are you using some other plugins/libraries with `flutter_file_picker`?

**Comment by ThinkDigitalRepair** [comment] 2018-10-20 20:38
It couldn't be other libraries because with the same project I provided,
it's the only dependency.

**Comment by ThinkDigitalRepair** [comment] 2018-10-21 16:30
It's android P on the Emulator and Oreo on the physical device

**Comment by sidlatau** [comment] 2018-10-27 18:03
As I understood compilation problem is related to your local environment, not the plugin. Closing an issue for now. If you have more information about the problem - feel free to share.

**Closed by sidlatau** 2018-10-27 18:03 UTC
